Feature/acquire task
suwahanauta/tasklist pull request #10
Opened 2024-03-25 10:27 UTC by suwahanauta

レスポンスとして返される情報にtasksという配列が見当たりませんでした。
コンソール出力部分のacquireの後にどんなプロパティを指定すればよろしいでしょうか？
　
　tasks: [
     {
　　　 id: string
　　　 title: string,
     }, ...
　　]
　}

2024-03-26 07:02 UTC, takiseHN requested changes

2024-03-26 07:02 UTC, takiseHN commented on app/taskList/page.tsx
> +    let [tasks, setTasks] = useState<string[]>([""])
"" を初期値にした理由はなんでしょうか

2024-03-26 07:02 UTC, takiseHN commented on app/taskList/page.tsx
> +                    if (task == "") {
ここの処理は何だろう？と感じました

2024-03-26 07:02 UTC, takiseHN commented on app/taskList/page.tsx
> +    const refFirstRef = useRef(true)
これは何のために使用しているのか

2024-03-26 07:09 UTC, suwahanauta commented on app/taskList/page.tsx
> +    let [tasks, setTasks] = useState<string[]>([""])
配列の要素の値をstring型に明治するために空文字を指定しました。
今初期値を指定しないことで空文字のp要素が作られないことを確認しました。

2024-03-26 07:10 UTC, suwahanauta commented on app/taskList/page.tsx
> +                    if (task == "") {
空文字のp要素が作成されてしまうため、taskの値が空の場合はmap関数を抜けるように追記しました。

2024-03-26 07:11 UTC, suwahanauta commented on app/taskList/page.tsx
> +    const refFirstRef = useRef(true)
useEffect が2回実行されてしまうのを防ぐためのコードだと認識しています。

2024-03-27 01:02 UTC, takiseHN commented on app/taskList/page.tsx
> +    type catchAPI = {
catchAPI だと分かりにくかったです

2024-03-27 01:02 UTC, merged